version: "2"
services:
  reverseproxy:
    image: nginx
    container_name: reverser-proxy
    hostname: reverse-proxy
    volumes:
      - ./containers/reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
  nginx:
    image: nginx
    container_name: domain-nginx.com
    hostname: domain-nginx.com
    volumes:
      - ./containers/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./containers/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./application-one:/usr/share/nginx/html/

  apache:
    image: httpd
    container_name: domain-apache.com
    hostname: domain-apache.com
    volumes:
      - ./containers/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./application-two:/usr/local/apache2/htdocs/
